### ISSUE TITLE
Can we add webcam as a input for inference?

### ISSUE THREAD

**Issue by nawinrajkumar** [AndreyGermanov/yolov8_onnx_rust#2]
Can we add a webcam as input using Videocapture? It would be very useful for deploying the code on Edge Devices as Rust has high inference rate. @AndreyGermanov

**Comment by AndreyGermanov** [comment]
Thanks for your interest!

The idea is great, but it goes out of scope of this repository, because this code related to the article, that already published.

So, this could be a great idea for a new project: to get video from a webcam in the browser and then send video frames to the Rust-backend for inference. 

I already wrote article about web browser part here: https://dev.to/andreygermanov/how-to-detect-objects-in-videos-in-a-web-browser-using-yolov8-neural-network-and-javascript-lfb. You can use frontend code from that article to get video frames from the web-camera, and then combine it with Rust code from this repository to implement inference of those frames on the backend.
